/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Hska
{
    public class LaneBoundary : Message
    {
        public const string RosMessageName = "hska_msgs/LaneBoundary";

        //  Contains an array of points and other details
        public const byte UNKNOWN = 0;
        public const byte SOLID = 1;
        public const byte DASHED = 2;
        public const byte SOLID_DASHED = 3;
        public const byte DASHED_SOLID = 4;
        public const byte SOLID_SOLID = 5;
        public byte style { get; set; }
        public const byte WHITE = 1;
        public const byte YELLOW = 2;
        public byte color { get; set; }
        public const byte OTHER = 0;
        public const byte DRIVING_LEFT = 1;
        public const byte DRIVING_RIGHT = 2;
        public byte line_pos { get; set; }
        //  Polynom coefficients polynom_coeffs[0], polynom_coeffs[1]*x, polynom_coeffs[2]*x^2, ...
        public double[] polynom_coeffs { get; set; }

        public LaneBoundary()
        {
            this.style = 0;
            this.color = 0;
            this.line_pos = 0;
            this.polynom_coeffs = new double[0];
        }

        public LaneBoundary(byte style, byte color, byte line_pos, double[] polynom_coeffs)
        {
            this.style = style;
            this.color = color;
            this.line_pos = line_pos;
            this.polynom_coeffs = polynom_coeffs;
        }
    }
}
