/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Hska;

namespace RosSharp.RosBridgeClient.MessageTypes.Hska
{
    public class LaneBoundaryArray : Message
    {
        public const string RosMessageName = "hska_msgs/LaneBoundaryArray";

        //  Contains an array of lane boundaries contained in a section or segment of road
        public Header header { get; set; }
        public uint min_look_ahead { get; set; }
        //  [m]
        public uint max_look_ahead { get; set; }
        //  [m]
        public uint img_width { get; set; }
        //  [pixel]
        public uint img_height { get; set; }
        //  [pixel]
        public float pixel_to_m { get; set; }
        public LaneBoundary[] boundaries { get; set; }

        public LaneBoundaryArray()
        {
            this.header = new Header();
            this.min_look_ahead = 0;
            this.max_look_ahead = 0;
            this.img_width = 0;
            this.img_height = 0;
            this.pixel_to_m = 0.0f;
            this.boundaries = new LaneBoundary[0];
        }

        public LaneBoundaryArray(Header header, uint min_look_ahead, uint max_look_ahead, uint img_width, uint img_height, float pixel_to_m, LaneBoundary[] boundaries)
        {
            this.header = header;
            this.min_look_ahead = min_look_ahead;
            this.max_look_ahead = max_look_ahead;
            this.img_width = img_width;
            this.img_height = img_height;
            this.pixel_to_m = pixel_to_m;
            this.boundaries = boundaries;
        }
    }
}
