/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Hska
{
    public class PedalCommand : Message
    {
        public const string RosMessageName = "hska_msgs/PedalCommand";

        //  Current Brake and Gas Pedal Command
        public Header header { get; set; }
        public float brake_pedal { get; set; }
        //  0 to 1.0
        public float gas_pedal { get; set; }
        //  0 to 1.0
        public bool active { get; set; }
        //  0 or 1 	

        public PedalCommand()
        {
            this.header = new Header();
            this.brake_pedal = 0.0f;
            this.gas_pedal = 0.0f;
            this.active = false;
        }

        public PedalCommand(Header header, float brake_pedal, float gas_pedal, bool active)
        {
            this.header = header;
            this.brake_pedal = brake_pedal;
            this.gas_pedal = gas_pedal;
            this.active = active;
        }
    }
}
