/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Hska
{
    public class SteeringCommand : Message
    {
        public const string RosMessageName = "hska_msgs/SteeringCommand";

        //  Current Steering Wheel Angle Command
        public Header header { get; set; }
        public bool reset_blinker_state { get; set; }
        //  0 -> no reset, 1 -> reset blinker state
        public float steering_angle { get; set; }
        //  Radian
        public bool active { get; set; }
        //  0 or 1

        public SteeringCommand()
        {
            this.header = new Header();
            this.reset_blinker_state = false;
            this.steering_angle = 0.0f;
            this.active = false;
        }

        public SteeringCommand(Header header, bool reset_blinker_state, float steering_angle, bool active)
        {
            this.header = header;
            this.reset_blinker_state = reset_blinker_state;
            this.steering_angle = steering_angle;
            this.active = active;
        }
    }
}
