/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Hska
{
    public class WheelRotationalSpeed : Message
    {
        public const string RosMessageName = "hska_msgs/WheelRotationalSpeed";

        //  Data of the Wheel Speed Sensors
        public Header header { get; set; }
        public float wheel_rot_speed_fl { get; set; }
        //  [1/s]
        public float wheel_rot_speed_fr { get; set; }
        //  [1/s]
        public float wheel_rot_speed_rl { get; set; }
        //  [1/s]
        public float wheel_rot_speed_rr { get; set; }
        //  [1/s]

        public WheelRotationalSpeed()
        {
            this.header = new Header();
            this.wheel_rot_speed_fl = 0.0f;
            this.wheel_rot_speed_fr = 0.0f;
            this.wheel_rot_speed_rl = 0.0f;
            this.wheel_rot_speed_rr = 0.0f;
        }

        public WheelRotationalSpeed(Header header, float wheel_rot_speed_fl, float wheel_rot_speed_fr, float wheel_rot_speed_rl, float wheel_rot_speed_rr)
        {
            this.header = header;
            this.wheel_rot_speed_fl = wheel_rot_speed_fl;
            this.wheel_rot_speed_fr = wheel_rot_speed_fr;
            this.wheel_rot_speed_rl = wheel_rot_speed_rl;
            this.wheel_rot_speed_rr = wheel_rot_speed_rr;
        }
    }
}
